#!/bin/bash
####################################
### setup with your credentials
####################################

# MOCK
export MockName=mock_name00

# AWS
export AWS-ClientId=AKIAZH5OR44MET22GVE7
export AWS-ClientSecret=MKfa9gM3/PIVKF8efP1e6SnolVuLGG+oGxdIIsfr

# Alibaba
export ALI-ClientId=LTAI4FsYEfNxz7XygcSKa2TX
export ALI-ClientSecret=Ve7ICDNQ2FRs9dJDEeAleZcquM2s9F

# Cloud-Twin
export CT1-IdentityEndpoint=http://52.193.131.187:8192
export CT1-DomainName=cloud-8
export CT1-MockName=mock_name-1

export CT2-IdentityEndpoint=http://52.193.131.187:8192
export CT2-DomainName=cloud-9
export CT2-MockName=mock_name-1


