#!/bin/bash
####################################
### setup with your credentials
####################################

# MOCK
export MockName=mock_name00

# AWS
export AWS-ClientId=xxxxxxxxxxxxxxxxxxxx
export AWS-ClientSecret=xxxxxxxxxxxxxxxxxxxxxxxxx

# Alibaba
export ALI-ClientId=xxxxxxxxxxxxxxxx
export ALI-ClientSecret=xxxxxxxxxxxxxxx

# Cloud-Twin
export CT1-IdentityEndpoint=http://xxx.xxx.xxx.xxx:8192
export CT1-DomainName=cloud-8
export CT1-MockName=mock_name-1

export CT2-IdentityEndpoint=http://xxx.xxx.xxx.xxx:8192
export CT2-DomainName=cloud-9
export CT2-MockName=mock_name-1


